[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200
via_ir = true
ignore = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/"
]

[profile.default.fuzz]
runs = 256

[profile.default.invariant]
runs = 256
depth = 15

[rpc_endpoints]
anvil = "http://127.0.0.1:8545"
sepolia = "${SEPOLIA_RPC_URL}"
story_testnet = "${STORY_TESTNET_RPC_URL}"
storyAeneid = "https://aeneid.storyrpc.io"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
